.\"
.\" Modified by Jeffrey Allen Neitzel, 2003, 2004.
.\"
.\" Changes by Gunnar Ritter, Freiburg i. Br., Germany, February 2001.
.\"
.\" Copyright(C) Caldera International Inc. 2001-2002. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"   Redistributions of source code and documentation must retain the
.\"    above copyright notice, this list of conditions and the following
.\"    disclaimer.
.\"   Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"   All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed or owned by Caldera
.\"      International, Inc.
.\"   Neither the name of Caldera International, Inc. nor the names of
.\"    other contributors may be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" USE OF THE SOFTWARE PROVIDED FOR UNDER THIS LICENSE BY CALDERA
.\" INTERNATIONAL, INC. AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL CALDERA INTERNATIONAL, INC. BE
.\" LIABLE FOR ANY DIRECT, INDIRECT INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
.\" EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" from .th IF I 5/2/74
.\" Sccsid @(#)if.1	1.2 (gritter) 2/13/02
.TH IF 1 "October 28, 2004" "osh-041028" "General Commands"
.SH NAME
if \- conditional command
.SH SYNOPSIS
.B if
\fIexpr\fR [\fIcommand\fR [\fIarg ...\fR]]
.SH DESCRIPTION
.I If
evaluates the expression
.IR expr ,
and if its value is true,
returns a zero exit status or executes the specified
.I command
with the given arguments.
Otherwise, a non-zero exit status is returned.
.PP
The following primaries are used to construct
.IR expr :
.TP 10n
.BI \-d \ file
True if \fIfile\fR exists and is a directory.
.TP
.BI \-e \ file
True if \fIfile\fR exists.
.TP
.BI \-f \ file
True if \fIfile\fR exists and is a regular file.
.TP
.BI \-h \ file
True if \fIfile\fR exists and is a symbolic link.
.TP
.BI \-r \ file
True if \fIfile\fR exists and is readable.
.TP
.BI \-s \ file
True if \fIfile\fR exists and has a size greater than zero bytes.
.TP
.BI \-t \ fildes
True if the file whose file descriptor number is
.I fildes
is open and associated with a terminal device.
.I Fildes
must be a decimal digit (0 - 9).
.TP
.BI \-w \ file
True if \fIfile\fR exists and is writable.
.TP
.BI \-x \ file
True if \fIfile\fR exists and is executable,
or if \fIfile\fR is a searchable directory.
.TP
.IB s1 \ = \ s2
True if the strings
.I s1
and
.I s2
are equal.
.TP
.IB s1 \ != \ s2
True if the strings
.I s1
and
.I s2
are not equal.
.TP
\fB{\fR \fIcommand\fR [\fIarg ...\fR] \fB}\fR
The \fIcommand\fR is executed with the given arguments
to obtain its exit status.
Status zero is \fItrue\fR.
.PP
These primaries may be combined with the following operators:
.TP 10n
.B !
unary negation operator
.TP
.B \-a
binary
.I and
operator
.TP
.B \-o
binary
.I or
operator
.TP
.BI ( \ expr \ )
parentheses for grouping.
.PP
.B \-a
has higher precedence than
.BR \-o .
Notice that all the operators and flags are separate arguments to
.I if
and hence must be surrounded by blanks.
Notice also that parentheses are meaningful
to the shell and must be escaped.
.SH "EXIT STATUS"
The
.I if
command exits with one of the following values:
.TP
0
The expression was true.
.TP
1
The expression was false or was not specified.
.TP
2
An error occurred.
.SH ENVIRONMENT
.TP
.B PATH
Is the sequence of directories used to search for command.
The
.I if
command from Sixth Edition
.SM UNIX
always used `.:/bin:/usr/bin', not
.SM PATH.
.SH "SEE ALSO"
goto(1),
osh(1),
sh6(1),
test(1)
.SH COMPATIBILITY
The
.I if
command from Sixth Edition
.SM UNIX
does not support the
.BR \-d ,
.BR \-e ,
.BR \-f ,
.BR \-h ,
.BR \-s ,
.BR \-t ,
and
.B \-x
operators.
.PP
In addition to supporting the above operators,
this port also differs from the original in that
the exit status returned varies according to whether
the expression is true or false,
as is the case with
.IR test (1).
