# Makefile.config for osh
#
# @(#)$Id$
#
# See INSTALL and Makefile for full details.
#

#
# Valentine's Day 2014 (Friday, 2014-02-14):
#
#	Twelve years ago today, Gunnar Ritter released osh as osh-020214.
#	Here's to 12 years of osh and UNIX love via osh-current and to
#	2014, the Year of Love <3
#

#
# The following specifies the osh date and version, where:
#
#   $X: major == decimal integer >= 4
#   $Y: minor == decimal integer >= 2
#   $Z: patch == decimal integer >= 0
#
#	osh-current            == current  development branch
#	osh-$X.$Y.$Z-beta[1-9] == beta     release
#	osh-$X.$Y.$Z           == official release ($Z == 0)
#	osh-$X.$Y.$Z           == patched  release ($Z >  0)
#
OSH_DATE=	October 20, 2016
OSH_VERSION=	osh-current
#
