# Makefile.config for osh
#
# @(#)$Id$
#
# See INSTALL and Makefile for full details.
#

#
# The following specifies the osh date and version:
#
#	osh-current            == current master branch development
#	osh-YYYYMMDD-current   == current development snapshot
#	osh-YYYYMMDD-beta[1-9] == beta     release
#	osh-YYYYMMDD           == official release
#	osh-YYYYMMDD-p[1-9]    == patched  release
#
OSH_DATE=	July 19, 2012
OSH_VERSION=	osh-current
