# Makefile.config for etsh
#
# @(#)$Id$
#
# See INSTALL and Makefile for full details.
#

#
# The following specifies the etsh date and version, where:
#
#   $X: major == decimal integer >= 4
#   $Y: minor == decimal integer >= 2
#   $Z: patch == decimal integer >= 0
#
#	etsh-current            == current  development branch
#	etsh-$X.$Y.$Z-beta[1-9] == beta     release
#	etsh-$X.$Y.$Z-test[1-9] == test     release (for debugging)
#	etsh-$X.$Y.$Z           == official release ($Z == 0)
#	etsh-$X.$Y.$Z           == patched  release ($Z >  0)
#
OSH_DATE=	August 8, 2017
OSH_VERSION=	etsh-current
